### ISSUE TITLE
cannot find sqlite3

### ISSUE THREAD

**Issue by CzarofAK** [SignalK/charts-plugin#16]
I tried to install charts-plugin on a Signal K server running on a Venus OS Large.
After installation the following status shows up:
`Failed to start: Cannot find module '/data/conf/signalk/node_modules/sqlite3/lib...`

**Comment by tkurki** [comment]
Something is missing from the installation. You can retry installing by running this command in `$HOME/.signalk`:

npm install --save @signalk/charts-plugin

and if that succeeds restart the server.

If you get error messages you can add them here to try to further debug the problem.

**Comment by CzarofAK** [comment]
Could not carry out your commands.
But after i installed Victron Venus from scratch and added the charts-plugin, the message does not appear anymore.
seems like it was related to a corrupt installation.
Tanks for the swift reply!
