### ISSUE TITLE
Does not work with online sources

### ISSUE THREAD

**Issue by VladimirKalachikhin** [SignalK/charts-plugin#21]
I create Open Topo Map chart provider by plugin interface. The `.signalk/plugin-config-data/charts.json` is:
```
{
  "configuration": {
    "onlineChartProviders": [
      {
        "name": "OpenTopoMap online",
        "minzoom": 1,
        "maxzoom": 18,
        "serverType": "tilelayer",
        "format": "png",
        "url": "https://b.tile.opentopomap.org/{z}/{x}/{y}.png"
      }
    ]
  },
  "enabled": true
}
```
I restart signalk-server, and:
```
$ curl localhost:3000/signalk/v1/api/resources/charts/open-topo-map-online
{"name":"OpenTopoMap online","bounds":[-180,-90,180,90],"minzoom":1,"maxzoom":18,"format":"png","scale":"N/A","identifier":"open-topo-map-online","tilemapUrl":"https://b.tile.opentopomap.org/{z}/{x}/{y}.png","type":"tilelayer","chartLayers":null}
```
Ok, chart is present.
But
```
$ wget localhost:3000/signalk/v1/api/resources/charts/open-topo-map-online/6/34/24
--2022-03-19 20:10:04--  http://localhost:3000/signalk/v1/api/resources/charts/open-topo-map-online/6/34/24
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2022-03-19 20:10:04 ERROR 500: Internal Server Error.
```
and signalk-server say "Unknown chart provider fileformat undefined".

However
```
$ wget localhost:3000/signalk/v1/api/resources/charts/world-coastline/6/34/24
--2022-03-19 20:20:02--  http://localhost:3000/signalk/v1/api/resources/charts/world-coastline/6/34/24
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [image/png]
Saving to: '24'

24                      [ <=>                ]  14.74K  --.-KB/s    in 0s      

2022-03-19 20:20:02 (99.4 MB/s) - '24' saved [15090]

```

So, the charts-plugin does not work with the online provider, but it works with offline.

**Comment by tkurki** [comment]
The idea with supporting online chart sources is that an application like Freeboard can get a list of charts from the server and then use them *directly*, so that the app, for example Freeboard running in a browser, requests them directly. This allows a central source of chart metadata in a system.

The Charts plugin does not work as a proxy. For external chart sources it only provides metadata "hey there's a chart in this address that you can use".

**Comment by VladimirKalachikhin** [comment]
This idea don't specified in charts-plugin doc. It says literally:
`GET /signalk/v1/api/resources/charts/${identifier}/${z}/${x}/${y} returns a single tile for selected chart`

**Comment by tkurki** [comment]
That is probably from the time when the plugin did not yet support online sources. Can you please submit an improvement?

**Comment by VladimirKalachikhin** [comment]
You ask if I can develop a map proxy for SignalK?

**Comment by tkurki** [comment]
No, just improve the misleading documentation.
